---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-admission-controller
  namespace: cluster-addons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-admission-controller
  template:
    metadata:
      labels:
        app: vpa-admission-controller
    spec:
      serviceAccountName: vpa-admission-controller
      containers:
        - name: admission-controller
          image: k8s.gcr.io/vpa-admission-controller:0.6.3
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --client-ca-file
            - /cert/ca.crt
            - --tls-cert-file
            - /cert/tls.crt
            - --tls-private-key
            - /cert/tls.key
          volumeMounts:
            - name: cert
              mountPath: "/cert"
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 200Mi
          ports:
            - containerPort: 8000
      volumes:
        - name: cert
          secret:
            secretName: vpa-webhook-cert
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-webhook
  namespace: cluster-addons
spec:
  ports:
    - port: 443
      targetPort: 8000
  selector:
    app: vpa-admission-controller
