apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vpa-webhook
  namespace: cluster-addons
spec:
  commonName: vpa-webhook.cluster-addons.svc
  secretName: vpa-webhook-cert
  issuerRef:
    name: vpa-webhook
